### ISSUE TITLE
ValueError: "ConversationEntityMemory" object has no field "store"

### ISSUE THREAD

**Issue by SteanlyCZ** [avrabyt/MemoryBot#1]
hi, 
this error appears with the latest version of the langchain library

**Comment by avrabyt** [comment]
Hi ! Thanks for raising the issue . 
I need to look onto it . Hard to keep up with the hourly release of LangChain 😅

**Comment by avrabyt** [comment]
> hi, this error appears with the latest version of the langchain library

Hi @SteanlyCZ , it's updated . Let me know.
